name: Tests

on: [ push, pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: Serious-senpai/genetic-algorithm
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build binary files in debug mode
        run: scripts/build.sh debug

      - name: Run pytest
        run: |
          export PYTHONPATH=$GITHUB_WORKSPACE
          pytest tests

      - name: Build binary files in release mode
        run: scripts/build.sh

      - name: Run pytest
        run: |
          export PYTHONPATH=$GITHUB_WORKSPACE
          pytest tests
